apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: user-addition
  namespace: ansible-tekton
spec:
  description:
    This Task is used to create the User via Ansible playbook cloned with git
  workspaces:
    - name: ansible-hosts
      mountPath: /etc/ansible
    - name: input-parameter
      mountPath: /etc/ansible/Tekton-git
    - name: validation-script
      mountPath: /home
    - name: git-clone
  steps:
    - name: host-validation
      image: ansible-user:v0.0.0
      script: |
         #!/usr/bin/env bash
         cd /home
         python validation.py /etc/ansible/Tekton-git/vars.yaml /etc/ansible/hosts
         if [[ $? -eq 0 ]]; then
            echo "Host verification is successful validation.Now, Ansible Playbook is ready to Execute"
         else
            echo "No Hosts are matched"
            exit 1
         fi

    - name: get-clone
      image: alpine-git:v0.0.1
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.git-clone.path)
        git clone https://<access token>@<git https url>
        ls -lrth
        chmod +x Tekton-git

    - name: ansible-playbook-execute
      image: ansible-user:v0.0.0
      script: |
        #!/usr/bin/env bash
        pwd
        cd $(workspaces.git-clone.path)
        ls -lrth
        cd Tekton-git
